CREATE TABLE IF NOT EXISTS law_schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aba_school_code TEXT UNIQUE,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    state CHAR(2) NOT NULL,
    region TEXT,
    website_url TEXT,
    is_aba_accredited BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT law_schools_name_city_state_key UNIQUE (name, city, state)
);

CREATE TABLE IF NOT EXISTS school_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    academic_year SMALLINT NOT NULL CHECK (academic_year BETWEEN 1900 AND 2100),
    total_enrollment INTEGER CHECK (total_enrollment >= 0),
    first_year_enrollment INTEGER CHECK (first_year_enrollment >= 0),
    median_gpa NUMERIC(3,2) CHECK (median_gpa BETWEEN 0.0 AND 4.0),
    median_lsat SMALLINT CHECK (median_lsat BETWEEN 120 AND 180),
    acceptance_rate NUMERIC(5,2) CHECK (acceptance_rate BETWEEN 0.0 AND 100.0),
    student_faculty_ratio NUMERIC(5,2) CHECK (student_faculty_ratio > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT school_statistics_school_year_key UNIQUE (law_school_id, academic_year)
);

CREATE TABLE IF NOT EXISTS employment_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    graduation_year SMALLINT NOT NULL CHECK (graduation_year BETWEEN 1900 AND 2100),
    employed_full_time_long_term NUMERIC(5,2) CHECK (employed_full_time_long_term BETWEEN 0.0 AND 100.0),
    employed_part_time NUMERIC(5,2) CHECK (employed_part_time BETWEEN 0.0 AND 100.0),
    employed_jd_required NUMERIC(5,2) CHECK (employed_jd_required BETWEEN 0.0 AND 100.0),
    employed_jd_advantage NUMERIC(5,2) CHECK (employed_jd_advantage BETWEEN 0.0 AND 100.0),
    unemployed_seeking NUMERIC(5,2) CHECK (unemployed_seeking BETWEEN 0.0 AND 100.0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT employment_outcomes_school_year_key UNIQUE (law_school_id, graduation_year)
);

CREATE TABLE IF NOT EXISTS bar_passage_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    jurisdiction TEXT NOT NULL DEFAULT 'Overall',
    exam_year SMALLINT NOT NULL CHECK (exam_year BETWEEN 1900 AND 2100),
    first_time_takers INTEGER CHECK (first_time_takers >= 0),
    first_time_pass_rate NUMERIC(5,2) CHECK (first_time_pass_rate BETWEEN 0.0 AND 100.0),
    ultimate_pass_rate NUMERIC(5,2) CHECK (ultimate_pass_rate BETWEEN 0.0 AND 100.0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT bar_passage_rates_school_jurisdiction_year_key UNIQUE (law_school_id, jurisdiction, exam_year)
);

CREATE TABLE IF NOT EXISTS tuition_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    academic_year SMALLINT NOT NULL CHECK (academic_year BETWEEN 1900 AND 2100),
    resident_tuition NUMERIC(12,2) CHECK (resident_tuition >= 0),
    nonresident_tuition NUMERIC(12,2) CHECK (nonresident_tuition >= 0),
    required_fees NUMERIC(12,2) CHECK (required_fees >= 0),
    living_expenses NUMERIC(12,2) CHECK (living_expenses >= 0),
    total_cost_of_attendance NUMERIC(12,2) CHECK (total_cost_of_attendance >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tuition_costs_school_year_key UNIQUE (law_school_id, academic_year)
);

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    gpa NUMERIC(3,2) NOT NULL CHECK (gpa BETWEEN 0.0 AND 4.0),
    lsat_score INTEGER NOT NULL CHECK (lsat_score BETWEEN 120 AND 180),
    geographic_preferences TEXT[] NOT NULL DEFAULT '{}',
    cost_sensitivity SMALLINT NOT NULL CHECK (cost_sensitivity BETWEEN 1 AND 5),
    lifestyle_preferences JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS career_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS law_school_career_paths (
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    career_path_id BIGINT NOT NULL REFERENCES career_paths(id) ON DELETE CASCADE,
    strength SMALLINT NOT NULL CHECK (strength BETWEEN 1 AND 5),
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (law_school_id, career_path_id)
);

CREATE TABLE IF NOT EXISTS user_profile_career_paths (
    user_profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    career_path_id BIGINT NOT NULL REFERENCES career_paths(id) ON DELETE CASCADE,
    preference_weight SMALLINT NOT NULL DEFAULT 3 CHECK (preference_weight BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_profile_id, career_path_id)
);

CREATE TABLE IF NOT EXISTS school_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    match_score NUMERIC(5,2) NOT NULL CHECK (match_score BETWEEN 0.0 AND 100.0),
    score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT school_matches_user_profile_school_key UNIQUE (user_profile_id, law_school_id)
);

CREATE INDEX IF NOT EXISTS idx_law_schools_state ON law_schools(state);
CREATE INDEX IF NOT EXISTS idx_law_schools_name ON law_schools(name);
CREATE INDEX IF NOT EXISTS idx_school_statistics_law_school_id ON school_statistics(law_school_id);
CREATE INDEX IF NOT EXISTS idx_school_statistics_academic_year ON school_statistics(academic_year);
CREATE INDEX IF NOT EXISTS idx_employment_outcomes_law_school_id ON employment_outcomes(law_school_id);
CREATE INDEX IF NOT EXISTS idx_employment_outcomes_graduation_year ON employment_outcomes(graduation_year);
CREATE INDEX IF NOT EXISTS idx_bar_passage_rates_law_school_id ON bar_passage_rates(law_school_id);
CREATE INDEX IF NOT EXISTS idx_bar_passage_rates_exam_year ON bar_passage_rates(exam_year);
CREATE INDEX IF NOT EXISTS idx_tuition_costs_law_school_id ON tuition_costs(law_school_id);
CREATE INDEX IF NOT EXISTS idx_tuition_costs_academic_year ON tuition_costs(academic_year);
CREATE INDEX IF NOT EXISTS idx_career_paths_slug ON career_paths(slug);
CREATE INDEX IF NOT EXISTS idx_law_school_career_paths_career_path_id ON law_school_career_paths(career_path_id);
CREATE INDEX IF NOT EXISTS idx_law_school_career_paths_strength ON law_school_career_paths(strength DESC);
CREATE INDEX IF NOT EXISTS idx_user_profile_career_paths_career_path_id ON user_profile_career_paths(career_path_id);
CREATE INDEX IF NOT EXISTS idx_user_profile_career_paths_preference_weight ON user_profile_career_paths(preference_weight DESC);
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON user_profiles(email);
CREATE INDEX IF NOT EXISTS idx_school_matches_user_profile_id ON school_matches(user_profile_id);
CREATE INDEX IF NOT EXISTS idx_school_matches_law_school_id ON school_matches(law_school_id);
CREATE INDEX IF NOT EXISTS idx_school_matches_match_score ON school_matches(match_score DESC);

INSERT INTO career_paths (slug, name, description)
VALUES
    ('biglaw', 'BigLaw', 'Large-firm corporate and transactional practice.'),
    ('government', 'Government', 'Work in federal, state, or local government roles.'),
    ('public-interest', 'Public Interest', 'Service-oriented advocacy and nonprofit legal work.'),
    ('judicial-clerkship', 'Judicial Clerkships', 'Clerking for judges after graduation.'),
    ('prosecutor', 'Prosecutor Careers', 'Criminal prosecution roles in public agencies.'),
    ('litigation', 'Litigation', 'Civil and commercial dispute resolution and trial practice.'),
    ('judicial-career', 'Judicial Careers', 'Long-term path toward service on the bench.')
ON CONFLICT (slug) DO NOTHING;