ALTER TABLE user_profiles
    DROP COLUMN IF EXISTS career_goals;

CREATE TABLE IF NOT EXISTS career_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS law_school_career_paths (
    law_school_id BIGINT NOT NULL REFERENCES law_schools(id) ON DELETE CASCADE,
    career_path_id BIGINT NOT NULL REFERENCES career_paths(id) ON DELETE CASCADE,
    strength SMALLINT NOT NULL CHECK (strength BETWEEN 1 AND 5),
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (law_school_id, career_path_id)
);

CREATE TABLE IF NOT EXISTS user_profile_career_paths (
    user_profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    career_path_id BIGINT NOT NULL REFERENCES career_paths(id) ON DELETE CASCADE,
    preference_weight SMALLINT NOT NULL DEFAULT 3 CHECK (preference_weight BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_profile_id, career_path_id)
);

CREATE INDEX IF NOT EXISTS idx_career_paths_slug ON career_paths(slug);
CREATE INDEX IF NOT EXISTS idx_law_school_career_paths_career_path_id ON law_school_career_paths(career_path_id);
CREATE INDEX IF NOT EXISTS idx_law_school_career_paths_strength ON law_school_career_paths(strength DESC);
CREATE INDEX IF NOT EXISTS idx_user_profile_career_paths_career_path_id ON user_profile_career_paths(career_path_id);
CREATE INDEX IF NOT EXISTS idx_user_profile_career_paths_preference_weight ON user_profile_career_paths(preference_weight DESC);

INSERT INTO career_paths (slug, name, description)
VALUES
    ('biglaw', 'BigLaw', 'Large-firm corporate and transactional practice.'),
    ('government', 'Government', 'Work in federal, state, or local government roles.'),
    ('public-interest', 'Public Interest', 'Service-oriented advocacy and nonprofit legal work.'),
    ('judicial-clerkship', 'Judicial Clerkships', 'Clerking for judges after graduation.'),
    ('prosecutor', 'Prosecutor Careers', 'Criminal prosecution roles in public agencies.'),
    ('litigation', 'Litigation', 'Civil and commercial dispute resolution and trial practice.'),
    ('judicial-career', 'Judicial Careers', 'Long-term path toward service on the bench.')
ON CONFLICT (slug) DO NOTHING;