ALTER TABLE school_statistics
    ADD COLUMN IF NOT EXISTS gpa_25th_percentile NUMERIC(3,2) CHECK (gpa_25th_percentile BETWEEN 0.0 AND 4.0),
    ADD COLUMN IF NOT EXISTS gpa_50th_percentile NUMERIC(3,2) CHECK (gpa_50th_percentile BETWEEN 0.0 AND 4.0),
    ADD COLUMN IF NOT EXISTS gpa_75th_percentile NUMERIC(3,2) CHECK (gpa_75th_percentile BETWEEN 0.0 AND 4.0),
    ADD COLUMN IF NOT EXISTS lsat_25th_percentile SMALLINT CHECK (lsat_25th_percentile BETWEEN 120 AND 180),
    ADD COLUMN IF NOT EXISTS lsat_50th_percentile SMALLINT CHECK (lsat_50th_percentile BETWEEN 120 AND 180),
    ADD COLUMN IF NOT EXISTS lsat_75th_percentile SMALLINT CHECK (lsat_75th_percentile BETWEEN 120 AND 180);

CREATE TABLE IF NOT EXISTS aba_509_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_checksum TEXT NOT NULL UNIQUE,
    report_year SMALLINT CHECK (report_year BETWEEN 1900 AND 2100),
    file_count INTEGER NOT NULL DEFAULT 1 CHECK (file_count >= 0),
    row_count INTEGER NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    status TEXT NOT NULL DEFAULT 'pending',
    notes TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);